### ISSUE TITLE
Istio with kubernetes on ubuntu

### ISSUE THREAD

**Issue by sakshi5195** [arun-gupta/java-k8s#8]
Hi,

I am trying to run istio with a sample application on kubernetes, on ubuntu environment. To do so, I have done the following steps:

1. Made an EC2 instance and connected to my linux machine using putty.
2. Followed basics steps to install kubernetes on the machine.
3. Installed Istio referring to various sites:
   (Deployed BookSamplInfo application present within the Isti package.)

    https://piotrminkowski.wordpress.com/2018/04/13/service-mesh-with-istio-on-kubernetes-in-5-steps/
    
    https://istio.io/docs/setup/kubernetes/quick-start/

    https://istio-releases.github.io/v0.1/docs/samples/bookinfo.html#cleanup

The issue faced :
After running -- kubectl get svc -n istio-system -- the external-ip of istio-ingressgateway is not being exposed. Thus, not being able to hit the deployed application. 

I tried using nodeport too, but it didn't help either.

Kindly guide me and specify the exact steps for using Istio, if possible.

**Comment by arun-gupta** [comment]
Istio installation steps are now clearly documented at https://github.com/arun-gupta/java-k8s#istio
