### ISSUE TITLE
Deploying the application using Helm is forbidden

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/java-k8s#9]
- Installed a new kops/k8s cluster
- Enabled default injection of sidecar proxy using
- Deployed the application using Helm
- Got the following error:

```
$ helm install --name myapp manifests/myapp
Error: release myapp failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "default"
```

Deploying directly using `app.yaml` works.

**Comment by arun-gupta** [comment]
Might be related to https://github.com/istio/istio/issues/5327

**Comment by christopherhein** [comment]
Check your `helm` version is it >2.9 this shouldn't happen with the >2.9 releases

**Comment by arun-gupta** [comment]
This is now working for EKS clusters.
